name: Create wiki data
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Create wiki data
        env:
          MAKE_VERSION: ${{ github.event.inputs.version }}
        run: |
          chmod +x gradlew
          ./gradlew run

      - name: Run data generator + Vanilla Exporter
        run: |
          cd ./run/runtime
          java -DbundlerMainClass=net.minecraft.data.Main -jar ../remapped/${{ github.event.inputs.version }}-server.jar --output=../data-gen --reports --server
          cd ../../vanilla-export
          sh ./vanilla-export.sh

      - name: Upload wiki data
        uses: actions/upload-artifact@v4
        with:
          name: wiki-data-${{ github.event.inputs.version }}
          path: run/output